# -*- coding: utf-8 -*-
"""residuo_apos_evaporacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ufp3VwnOjAyTIfya9GLCmunvcDTBX4L9
"""


def residuo():
    # Variáveis
    tara = float(input('Digite a massa do béquer que você utilizou (em gramas): '))
    volume = float(input('Digite o volume da amostra (em mL): '))
    final = float(input('Digite a massa do béquer após a evaporação da amostra (em gramas):'))

    # Resposta
    resposta = 1e6 * ((final - tara)/volume)

    # Saída
    print(f'A sua amostra contém %.2f mg/L de resíduo após evaporação' % resposta)


if __name__ == '__main__':
    residuo()
