# -*- coding: utf-8 -*-
"""solucoes_acidas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1khYPX-t5KIvnQT_SXtSRlXzDgyPqRAeX
"""


def volume():
    print('Bem vindo a calculadora de soluções!')
    volume_final = float(input('Qual o volume desejado da solução final (em Litros)? '))
    concentracao = float(input('Qual é a concentração dessa solução (em mol/L)? '))
    massamolar = float(input('Qual a massa molar desse ácido (em g/mol)? '))
    densidade = float(input('Qual a densidade do ácido utilizado (em g/mL)? '))
    pureza = float(input('Por último, qual a pureza desse ácido (em %): '))
    v = ((100 * massamolar * concentracao * volume_final) / (pureza * densidade))
    print(f'Para fazer {volume_final} litros da solução, você precisará de %.2f' % v + 'mL do ácido desejado')


if __name__ == '__main__':
    volume()

