# -*- coding: utf-8 -*-
"""teor_de_cinzas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15BKurAqH1LPvTXcQUfzgIzZguaXE2lZH
"""


def teor():
    tara = float(input('Digite a massa da cápsula vazia (em gramas): '))
    p1 = float(input('Digite a massa da amostra (em gramas): '))
    p2 = float(input('Digite a massa da cápsula + amostra após secagem (em gramas): '))
    cinzas = (p2 - tara / p1) * 100
    print(f'O teor de cinzas da amostra é %.2f' % cinzas + '%')


if __name__ == '__main__':
    teor()
