# -*- coding: utf-8 -*-
"""teor_de_umidade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJcQDDctWxEd2ItSmuG-5xa_thQ552tU
"""


def teor():
    tara = float(input('Digite a massa da cápsula vazia (em gramas): '))
    p1 = float(input('Digite a massa da amostra (em gramas): '))
    p2 = float(input('Digite a massa da cápsula + amostra após secagem (em gramas): '))
    umidade = (1 - ((p2 - tara)/p1)) * 100
    print(f'O teor de umidade da amostra é %.2f' % umidade + '%')


if __name__ == '__main__':
    teor()
